log_debug: true
hack_me_please: true
server:
  http:
    listen_addr: ':80'
    # allowed_networks: ['101.255.157.11']
users:
  - name: 'ramdan'
    password: 'ramdan'
    to_cluster: 'cluster_1S_2R'
    to_user: 'default'
    max_execution_time: 30s
    allow_cors: true
clusters:
  - name: 'cluster_1S_2R'
    nodes: ['clickhouse-01:8123', 'clickhouse-02:8123']
    users:
      - name: 'default'
        password: 'password123'