log_debug: true
hack_me_please: true
server:
  http:
    listen_addr: ':80'
    # allowed_networks: ['101.255.157.11']
users:
  - name: '${USERNAME_PROXY}'
    password: '${PASSWORD_PROXY}'
    to_cluster: 'cluster_1S_2R'
    to_user: '${USERNAME_NODES}'
    max_execution_time: 30s
    allow_cors: true
clusters:
  - name: 'cluster_1S_2R'
    nodes: ['103.176.79.206:8124', '103.127.132.33:8125']
    users:
      - name: '${USERNAME_NODES}'
        password: '${PASSWORD_NODES}'